Fix annotation
Evrard-Nil/kico pull request #19
Opened 2021-02-11 17:08 UTC by samylegalloudec

2021-02-12 09:03 UTC, ThomasHerbe approved these changes

2021-02-13 17:16 UTC, ThomasHerbe requested changes

2021-02-13 17:16 UTC, ThomasHerbe commented on front-end/src/app/components/ac-image-annotator/ac-image-annotator.component.ts
>      this.idVideo = 'b50905c7-de74-40c6-9d7f-bbedafc98c9f';
Tu peux supprimer

2021-02-16 13:20 UTC, samylegalloudec commented on front-end/src/app/components/ac-image-annotator/ac-image-annotator.component.ts
>      this.idVideo = 'b50905c7-de74-40c6-9d7f-bbedafc98c9f';
Done

2021-02-16 13:20 UTC, ThomasHerbe approved these changes

2021-02-16 13:20 UTC, merged