Annotation video
Evrard-Nil/kico pull request #7
Opened 2020-11-20 16:10 UTC by samylegalloudec

2020-11-21 10:10 UTC, ThomasHerbe commented on front-end/src/app/app.component.html
> +<app-ac-image-view></app-ac-image-view>
Si tu mets ton composant ici, il sera partagé sur toutes les pages de l'application, faudrait plutôt qu'il soit spécifique à ton composant de page

2020-11-21 10:13 UTC, ThomasHerbe commented on front-end/src/app/components/ac-image-annotator/ac-image-annotator.component.html
> +<button id="undo" (click)="undoAction()">Undo</button>
Tu peux supprimer ces commentaires comme tu as défini les boutons dans un autre html

2020-11-21 10:18 UTC, ThomasHerbe requested changes
Juste un déplacement de composant.
Il faudra également définir la routes vers ton composant dans le fichier de routing

2020-11-22 13:02 UTC, samylegalloudec commented on front-end/src/app/app.component.html
> +<app-ac-image-view></app-ac-image-view>
Ah oui bien vu c'est un oubli, l'idée c'est qu'il soit appelé par le composant  de Flo. Je le retire d'ici, et je laisse @Florian-Le-Menn l'ajouter au menu.

2021-01-05 13:13 UTC, merged